### ISSUE TITLE
Why is skipper necessary? 

### ISSUE THREAD

**Issue by seivan** [zalando-incubator/kube-ingress-aws-controller#109]
I don't understand why Skipper or any other form of internal load balancer Nginx would be necessary for this to work?  Shouldn't `ALB` be sufficient on its own? What am I missing?

**Comment by szuecs** [comment]
ALB has the limitation of number of routes to 50 and has no path routing.

Skipper is just a suggestion, what we know works at scale and we are using in production since 1y in kubernetes and outside more than 2y.
Nginx has a lot of drawbacks if you have rapidly changing endpoints and it's not made for this. 

Skipper is pretty simple to setup, no configmap for example and we only have 3 poewerful annotations, which you an optionally use to do feature toggles, circuit breaking, rate limiting, blue-green deployments and this is only a few patterns you can use to get more resilient services using that infrastructure component, without having complexity of istio.

**Comment by seivan** [comment]
Yeah it makes sense. But I am curios over if I can use this without Skipper?
I am not interested in path routing and won't have more than 10 nodes. What I do need is Websocket support which existing ELB (Classical) doesn't do well. 

Thanks for allowing me to use the issues to ask a question. I appreciate it.

**Comment by szuecs** [comment]
You can also pipe websockets through skipper. It called --experimental-upgrade (or similar top of my head ;) ) flag to enable it. We use it also in production so experimental part is more than 1 year ago.
I understand thyt you want ot have a minimal setup and I bet you can do this if you use hostNetwork=true in your deployment and point the Target group to that port. Skipper is also deployed like this, so it should work  also if you point to your own application.

**Comment by seivan** [comment]
I thought `hostNetwork` was deprecated or to be avoided in general? 
I don't think I quite understood. Is it not possible (as of today, out of the box) to use this without Skipper? 

Just pointing the load balancers to my app service (that has 4 pods through a DaemonSet)?

**Comment by szuecs** [comment]
You don't need a daemonset, but the port listening on the EC2 node network has to be in the targetgroup of the ALB.
You can use a service mentioned in
https://kubernetes.io/docs/concepts/configuration/overview/#services

**Comment by seivan** [comment]
You don't happen to have an example of this? It sounds like it has not been tested?

**Comment by szuecs** [comment]
skipper production configuration we use: https://github.com/zalando-incubator/kubernetes-on-aws/blob/dev/cluster/manifests/skipper/daemonset.yaml
ingress controller that creates ALBs: https://github.com/zalando-incubator/kubernetes-on-aws/blob/dev/cluster/manifests/ingress-controller/deployment.yaml

This setup runs in production since 1 year. Of course you can do it differently if you like.

**Comment by szuecs** [comment]
I will close this, please reopen if something is unclear or we can do better to fix your issue
