### ISSUE TITLE
Use Custom Tag for Discovery

### ISSUE THREAD

**Issue by grifonas** [zalando-incubator/kube-ingress-aws-controller#116]
Hi All,

The Ingress Controller is currently using the ```aws:autoscaling:groupName``` tag.

In our setup, however, some of the nodes are managed by a custom system rather than an autoscaling group.

Which leads me to the following questions:
1. Is it possible to customise the tag the Ingress Controller uses for discovery?

When trying to run the controller on a node not created by an AS group we're getting the following error:
```bash
2017/12/24 14:58:40 starting /bin/kube-ingress-aws-controller
2017/12/24 14:58:41 instance is missing the "aws:autoscaling:groupName" tag
```
2. Can the ingress-controller be ran as a daemon set? This will make sure that all the instances are discovered regardless of what autoscaling group (if any) they were created by.

**Comment by szuecs** [comment]
Hi! Thanks for describing this issue. 

1. Not right now, but this is a doable enhancement we should tackle as sooner as better.
As you have written we use `aws:autoscaling:groupName` to identify the nodes for the targetGroup of the ALBs created by this ingress controller

2. This will not provide the value you assume I think. I think in general we should use a custom Tag to identify the target nodes, that we should be able to create via ASG or manual (automated by the user).

Does this makes sense to you?

**Comment by mikkeloscar** [comment]
To add to what @szuecs already said so far we have assumed that all the instances attached to the ALB is in an autoscaling group because it makes it very simple for the controller. We can have AWS attach/dettach instances from the ALB automatically without worrying about this logic in the controller.

For your use case, and for the use case of using spot instances/fleets (#105) we will probably need to implement this logic ourselves as there currently is no automatic way like with ASGs.

So in my mind we would need to do something like this continuously:

1. Discover all instances belonging to the cluster (possibly filtering by some other tag to only select those that should be used by the ALB).
2. Attach all instances to the ALB
3. Remove instances from ALB which should no longer be attached e.g. because they are terminating. (Maybe AWS does something automatic here, I'm not completely sure how this works).
4.  Go back to 1 and start over.

**Comment by grifonas** [comment]
Hi @szuecs  and @mikkeloscar!
Thanks very much for your responses.
What you both said makes perfect sense. 

I suppose one could simply replace the value for the "autoScalingGroupNameTag" variable in ec2.go with the value taken from an environment variable that could in turn be provided in the controller manifest, couldn't one? It can fall back to "aws:autoscaling:groupName" if nothing's provided.

This would be a simple enough change, don't you think?

Thanks again!

**Comment by szuecs** [comment]
@grifonas yes that we can easily do as "workaround" without harm. We should pass it through the adapter manifest and set a package variable. The current autoScalingGroupNameTag can be used as default if an empty value is set. Doyou like to contribute this change @grifonas or should we do it as soon as we have time?

@mikkeloscar any thoughts on that?

**Comment by mikkeloscar** [comment]
The problem is just that making the tag name custom wont do anything as the current implementation needs an ASG name in order to create the Target group. So we need to implement custom logic for attaching/detaching individual instances to an ALB/target group as well.

I'm not saying we shouldn't do it, just pointing out it's a bit more effort.

Also regarding the tag name maybe we should consider if it makes sense to implement it such that instances in an ASG are attached like now via a single Target Group and then all other instances, identified by *some* tag are attached individually.

**Comment by mikkeloscar** [comment]
This was done in #118
