### ISSUE TITLE
support for AWS WAF

### ISSUE THREAD

**Issue by sstarcher** [zalando-incubator/kube-ingress-aws-controller#164]
I would be great to be able to configure a AWS WAF in front of the ALB.

**Comment by szuecs** [comment]
Hi!
Makes sense to me, but can you please specify what exactly you want to specify and how this should be configured?
I never used it myself. 

For example ingress annotation `aws-waf: <name>`
or `aws-waf-regexp: <re2-regexp>`

**Comment by sstarcher** [comment]
For my use-case `aws-waf: <name>` would be sufficient and a great addition

**Comment by greenboxal** [comment]
:+1:

@szuecs Something related that still bugs me, how do you guys keep in sync resources that need to be created outside K8S?

I have this problems with security groups, IAM roles (for use with kube2iam), S3 buckets and other resources. Today I create those extra resources with Terraform and "hope" that name defined on Kubernetes annotations are the same.

If WAF support is added we would have the same problem.

**Comment by szuecs** [comment]
@greenboxal it depends, but most of the time the solution is to crash and let kubelet restart your container.
SG are really nasty, because AWS does not send a RST packet, from network point of view I consider this as bug, but most network/firewall engineers I know think this as a security feature to drop silently a packet (security by obscurity in my point of view).
kube2iam specific: use init container in your pod to validate that the node already got the iam role, if it does not have it crash the init container.

For WAF I would not care so much. We would only configure WAF if you set a rule or name in the annotation and let cloudformation figure dependenices out. What do you think can hurt if WAF rule is not yet applied and you have an ALB or do you have any other scenario that might be a problem?

**Comment by janario** [comment]
It would be great to have that, we have steps that have to be executed right after the ALB creating, in order to keep it secure

I've sent a PR https://github.com/zalando-incubator/kube-ingress-aws-controller/issues/164

Please take a look :)

**Comment by szuecs** [comment]
@janario thanks for the PR. Your implementation does a fixed WAF rule, that is passed via CLI flag, which is fine and a step forward. 
Do you want to also have one with ingress annotation with opt-in or opt-out of the fixed WAF from CLI params to the controller?

**Comment by szuecs** [comment]
I assume that, you need to force to create another ALB.
We already have a similar annotation `zalando.org/aws-load-balancer-shared: "false"` to force a non shared ALB. I see 3 solutions for this:
1. Document that you need to set `zalando.org/aws-load-balancer-shared: "false"`, if you want to set a non default WAF rule or you get undefined behavior (not really safe if only one ingress wants to have a WAF and rest will get a WAF, because of one ingress)
2. Force a WAF ID which is != default WAF to have the same behavior as `zalando.org/aws-load-balancer-shared: "false"` (seems to me a simple solution to add)
3. a WAF ID which is != default WAF is able to find similar ingress to create a shared ALB to group by WAF ID. (most featurefull, but maybe overkill)

**Comment by szuecs** [comment]
#238 is the follow up for enhancing WAF support

**Comment by szuecs** [comment]
Feature was released https://github.com/zalando-incubator/kube-ingress-aws-controller/releases/tag/v0.8.3
