### ISSUE TITLE
Cert matching can select non trusted certificates

### ISSUE THREAD

**Issue by szuecs** [zalando-incubator/kube-ingress-aws-controller#211]
We should support non trusted (self signed) certificates, but if we have similar matching results we should not just select the newer one, but check if both are trusted first and pick the trusted before checking "newer".

**Comment by aermakov-zalando** [comment]
This will not really work. You can't have both non-trusted and valid certificates matching the same hostname on the same ELB, because then one of the clients will not be able to verify (either the one that uses proper roots, or the one that uses private roots). If we really need to be able to use non-trusted certificates, I'd rather force the users to explicitly specify the ARN and then split them out to a dedicated ELB, but for now I'd rather skip them completely.
