### ISSUE TITLE
Support Ingress annotations from aws-alb-ingress-controller

### ISSUE THREAD

**Issue by njuettner** [zalando-incubator/kube-ingress-aws-controller#261]
https://kubernetes-sigs.github.io/aws-alb-ingress-controller/guide/ingress/annotation/

We also should support dualstack.

**Comment by mikkeloscar** [comment]
Dualstack support was added here it: https://github.com/zalando-incubator/kube-ingress-aws-controller/pull/209

**Comment by szuecs** [comment]
Annotations are specific to controllers, so I believe we can support some features, but not their annotations. Their mapping is also very different from this controller. They use: `ALB -> nodeport service -> pods`
This one use `ALB/NLB -> hostport -> pods`, and hostport can be skipper to do the routing.

Therefore I will close this issue, because DualStack is already supported.
