### ISSUE TITLE
Can we use controller-id as part of Cloudformation stack names?

### ISSUE THREAD

**Issue by icy** [zalando-incubator/kube-ingress-aws-controller#297]
Now every deployment of the controllers ends up in the similar names in Cloudformation stacks. The naming function just generates stack name from cluster name and the uuid (FIXME) of the namespace:

https://github.com/zalando-incubator/kube-ingress-aws-controller/blob/dd568411e964a6d2e06c96836bb348cbc9a37f7a/aws/naming.go#L25

I don't think this is better than using controller id name. After a few migration steps, we have a few stacks and it' taking so much effort to learn which one is being used, which one should be deleted...

Thanks a lot.

**Comment by icy** [comment]
Fyi, it's also possible to find the stack name from logs, e.g.,

```
kubectl logs -n kube-system -l component=ingress --tail=1000000|grep cloudformatio
```
but it's not so convenient.

**Comment by szuecs** [comment]
Sounds ok to me to have the controller-id also in the name.
I am not sure how long the name is allowed to be, so this could be the only problem I see.

**Comment by icy** [comment]
I would spend time to have a PR. Thanks for your input.

**Comment by mikkeloscar** [comment]
If we put the controller-id in the stack-name there are a lot of edge cases which has to be considered and I don't see what the real value is other than identifying the stack quickly. It is already on the tags of stacks so you can look there.

The edge cases I'm talking about is:
* you can't rename a stack so you can't manually change ownership if you wanted to
* Stack names are limited so if you exceed the limit you have to shorten the name and make sure you do this in a way which won't conflict with other controller-ids/stacks.
* The stack is just a resource with an ID, we shouldn't have to encode the owning controller-id there as we already have it as a tag.

So I'm not in favor of this feature. If we add it I would at least want it to be opt-in rather than the default.

**Comment by szuecs** [comment]
I agree with @mikkeloscar.
I normally just copy and paste the status field from the ingress into the search field to filter loadbalancers.
I also think that you can easily use a tags filter with aws cli, but on the other hand if you want to have it and you add an option to opt-in then I have nothing against it.
I would not like to have fallbacks if name is too long if we not already have one, because it would only make the code more ugly.

**Comment by szuecs** [comment]
@icy do you think it's valuable to work on this or should we close it?

**Comment by icy** [comment]
Sorry for the late update @szuecs .. I tried to fork to add tagging support, but I'm too busy to push now. I will re-open the ticket when the PR is ready. Thanks a lot.
