### ISSUE TITLE
omit LB creation for cluster.local domain (was: adding a load balancer type none)

### ISSUE THREAD

**Issue by szuecs** [zalando-incubator/kube-ingress-aws-controller#308]
In order to support [cluster internal east-west routing](https://opensource.zalando.com/skipper/kubernetes/east-west-usage/) without having an assigned load balancer we should create a `zalando.org/aws-load-balancer-type: none`, such that users can opt-out the load balancer creation and external-dns would not create a DNS name for it.

Why not using class to opt-out selection of this ingress-controller? 
Because you might want to run it as default ingress controller such that it will pick up the ingress anyways.

**Comment by mikkeloscar** [comment]
I would rather that we define something like an internal zone e.g. `cluster.local` via a flag or so. And any ingress which specifies a hostname with the `.cluster.local` zone will not get a load balancer *unless* there is also another hostname defined.

with the `zalando.org/aws-load-balancer-type: none` annotation, you can't have both an internal and external name and the user has to explicitly opt-out rather than simply opting in by specifying a "public" host name for which we can create a load balancer with SSL.

**Comment by szuecs** [comment]
@mikkeloscar true, but we have already the automated provisioning via east-west.
Anyways I think your idea makes sense, let’s do that!
