### ISSUE TITLE
Update ALB Security Policy instead of creating a new ALB

### ISSUE THREAD

**Issue by adri** [zalando-incubator/kube-ingress-aws-controller#339]
Hi 👋 

my goal is to update the SSL Policy config of an ALB managed by kube-ingress-aws-controller v0.9.6.

In my tests, I see that a new CloudFormation stack is created when I set the default `ssl-policy` on the ingress controller deployment. When creating a new CloudFormation stack, also a new load balancer is created and external-dns moves over the Route53 entries to the new load balancer. 

However we had issues in the past where not all DNS caches are updated and the old load balancer was removed. Is there a way to update the CloudFormation stack to update the Security  Policy to avoid changing DNS entries?

I think this line decides to not match the ingress with the load balancer:
https://github.com/zalando-incubator/kube-ingress-aws-controller/blob/master/worker.go#L93
Is that on purpose? Is there another way to set the Security Policy without potential downtime?

**Comment by szuecs** [comment]
SSLpolicy can’t be in general changed in place.
Let’s say you have 20 ingress and you change the policy on one....
I think the best would be to have longer ttl value for cf stack deletion. We already have a ttl which could be increased.
Maybe you can check if you already can do that. Or @mikkeloscar can check and answer 😇

**Comment by adri** [comment]
hi @szuecs, thanks! That stack TTL sounds like a good idea in any case. 

Looks like it's added in this [commit](https://github.com/zalando-incubator/kube-ingress-aws-controller/commit/200d71a59104dd9449679f0c07efab369c58d314), however I don't see a way to modify it from outside. The default is set to 5 minutes, but the commit messages says 1h 🤔 
I'd set that to 48 hours to be sure most DNS caches are updated. Do you imagine a PR or making this configurable?

**Comment by szuecs** [comment]
You are right it’s 5 minutes right now https://github.com/zalando-incubator/kube-ingress-aws-controller/blob/master/aws/adapter.go#L83, because we tested it and forget to change it.
A PR can be done if you check for example the idle connection timeout in https://github.com/zalando-incubator/kube-ingress-aws-controller/blob/master/aws/adapter.go#L265 and the worker.go file.
Can you create a PR, please?

**Comment by szuecs** [comment]
@mikkeloscar maybe you have time to fix it?

**Comment by adri** [comment]
I tested with setting the stack termination protection, but although it was enabled the stack was deleted after 30 minutes. So that's not an option :)

However I also tested with just changing the SSL Policy manually and that worked. I've also tested updating the stack parameter `ListenerSslPolicyParameter` and it's possible to update the current stack instead of creating a new stack when the policy changes.

I think these are two different things: 
1. Should stack parameters be updated instead of create stack & delete stack?
2. If a stack needs to be deleted, how to keep the old stack around longer, to avoid downtime for slow updating DNS clients?

How do you handle the deletion of these stacks? Is that not an issue for you?

**Comment by szuecs** [comment]
What I was trying to say is, that please create a pr to increase the ttl, set via flag to the controller similar to features like the `idle connection timeout` setting.
Update is only possible if all ingresses want to have the same configuration, that’s why it creates a new stack.
I would recommend to increase the ttl via flag and increase the default to what was documented 1h instead of 5m.

Sounds good?

**Comment by adri** [comment]
Thanks a lot for all your information!

The solution for us is to use `--cert-ttl-timeout=24h` to give more time for DNS to propagate the load balancer endpoint change.
